// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVlcSbmj56gblCtMh0O4nyodTlKLGkS6Y',
    appId: '1:204143229074:web:5648823057de41ed254e4b',
    messagingSenderId: '204143229074',
    projectId: 'notes-app-1233211',
    authDomain: 'notes-app-1233211.firebaseapp.com',
    storageBucket: 'notes-app-1233211.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0O_w9wWatX9p9hFIrnR0yvTypd3RfpiE',
    appId: '1:204143229074:android:48e48e6730274fd6254e4b',
    messagingSenderId: '204143229074',
    projectId: 'notes-app-1233211',
    storageBucket: 'notes-app-1233211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_6J43SyAPgNGbJ9v_joMQXEJfE660f-o',
    appId: '1:204143229074:ios:68f353b481beb235254e4b',
    messagingSenderId: '204143229074',
    projectId: 'notes-app-1233211',
    storageBucket: 'notes-app-1233211.appspot.com',
    iosClientId: '204143229074-o744aa80o8esru3q0fi0gv2ptf3cpet0.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_6J43SyAPgNGbJ9v_joMQXEJfE660f-o',
    appId: '1:204143229074:ios:68f353b481beb235254e4b',
    messagingSenderId: '204143229074',
    projectId: 'notes-app-1233211',
    storageBucket: 'notes-app-1233211.appspot.com',
    iosClientId: '204143229074-o744aa80o8esru3q0fi0gv2ptf3cpet0.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
